### PR TITLE
Added Auth0

### LINKED ISSUE #2: Log out function
- Log out functionality

### PR DESCRIPTION
**Pull request by lesleychard**
Resolves #2 

- Simple log in with Auth0 config (personal account for testing for now)
- Added log out

### CODE REVIEW

**Review by BurtonTechnical — APPROVED** [review]
Looks good. I'm assuming the auth0 configuration is strictly prototyping, and there's someone at MUN to handle the domain and key at some point, but other than that this is pretty slick. I'm gonna learn how to write better React off this , which is a great bonus.

**Comment by whymarrh** [comment]
There are a few stray `console.log`s but looks good!

**Comment by lesleychard** [comment]
> There are a few stray `console.log`s but looks good!

Those are resolved in future PRs, left in for testing purposes

**Comment by lesleychard** [comment]
> Looks good. I'm assuming the auth0 configuration is strictly prototyping, and there's someone at MUN to handle the domain and key at some point, but other than that this is pretty slick. I'm gonna learn how to write better React off this , which is a great bonus.

We will be managing the Auth0 domain, but someone from MUN will be managing the users.

**Pull request merged**
